exports.superadminDummy = [
  {
    email: "superadmin@esee.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    adminLevel: "superadmin",
    lastName: "Doe",
    firstName: "Jane",
    birthDate: "1999-01-25",
    gender: "Female",
    address: "219 Denesik Ridge Shreveport, LA 71107",
    country: "United States",
    avatarImageUrl: "https://i.ibb.co/f1mfXp8/istockphoto-564567808-612x612.jpg",
    mobileNumber: "+15367012635",
    hasConfirmedEmail: true,
    createdBy: null,
  }
];

exports.adminDummy = [
  {
    email: "zelma.durgan@esee.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    adminLevel: "admin",
    lastName: "Durgan",
    firstName: "Zelma",
    birthDate: "1995-04-22",
    gender: "Female",
    address: "42687 Pansy Hill Apt. 855 Gold Beach, OR 97444",
    country: "United States",
    avatarImageUrl: "https://i.ibb.co/2ZGVm2F/1.jpg",
    mobileNumber: "42687 Pansy Hill Apt. 855 Gold Beach, OR 97444",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    email: "schoen.cristopher@esee.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    adminLevel: "admin",
    lastName: "Schoen",
    firstName: "Cristopher",
    birthDate: "1990-07-30",
    gender: "Male",
    address: "56 Jalan Hahn Park",
    country: "Singapore",
    avatarImageUrl: "https://i.ibb.co/vZnBf9r/2.jpg",
    mobileNumber: "+656133 9888",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    email: "thomas.oliver@esee.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    adminLevel: "admin",
    lastName: "Thomas",
    firstName: "Oliver",
    birthDate: "1999-02-21",
    gender: "Male",
    address: "74 Griffiths FerryEdwardsmouthPL9 9NN",
    country: "United Kingdom",
    avatarImageUrl: "https://i.ibb.co/TTt8nqz/3.jpg",
    mobileNumber: "03544 98853",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    email: "rachel.cruz@esee.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    adminLevel: "admin",
    lastName: "Cruz",
    firstName: "Rachel",
    birthDate: "1999-01-10",
    gender: "Female",
    address: "69A Ernser Squares Suite 173, Shariff Saydona Mustapha 8494 Aklan",
    country: "Philippines",
    avatarImageUrl: "https://i.ibb.co/9twTxFP/4.jpg",
    mobileNumber: "703-834-957",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
]

exports.hostsDummy = [

  {
    id: "34638",
    email: "stevie.smith@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Smith",
    firstName: "Stevie",
    birthDate: "1999-01-05",
    gender: "Male",
    address: "6739 Schimmel Heights Suite 543 Basalt, CO 81621",
    country: "Philippines",
    mobileNumber: "+1 (525) 389-7088",
    avatarImageUrl: "https://i.ibb.co/TbQvhBP/1.jpg",
    upliveName: "Stevie",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Adolf Waelchi",
    referralName: "Zander Beer",
    specialTalent: "Singing",
    videoLink: "https://www.youtube.com/",
    recruitmentDate: "2022-01-25",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    id: "73538",
    email: "william.armstrong@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Armstrong",
    firstName: "William",
    birthDate: "1997-05-05",
    gender: "Male",
    address: "7356 April Route Apt. 315 Anselmo, NE 68813",
    country: "Philippines",
    mobileNumber: "+1-979-566-8940",
    avatarImageUrl: "https://i.ibb.co/T22sPVN/2.png",
    upliveName: "William",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Verner Walsh",
    referralName: "Aidan Upton",
    specialTalent: "Singing",
    videoLink: "https://www.youtube.com/",
    recruitmentDate: "2022-01-10",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    id: "93995",
    email: "haleigh.eichmann@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Eichmann",
    firstName: "Haleigh",
    birthDate: "1994-01-28",
    gender: "Male",
    address: "8121 Ozella Pass Apt. 029 Weaverville, NC 28787",
    country: "Hong Kong SAR China",
    mobileNumber: "+1-686-966-3317",
    avatarImageUrl: "https://i.ibb.co/9h75n4h/3.jpg",
    upliveName: "Haleigh",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Michel Hilpert",
    referralName: "Hiram Fisher",
    specialTalent: "Dancing",
    videoLink: "https://www.youtube.com/",
    recruitmentDate: "2022-03-05",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    id: "19374",
    email: "reichel.newton@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Reichel",
    firstName: "Newton",
    birthDate: "2000-10-12",
    gender: "Male",
    address: "57088 Halle Wells Apt. 043 Lewis Center, OH 43035",
    country: "Albania",
    mobileNumber: "509-576-2464 x096",
    avatarImageUrl: "https://i.ibb.co/bgGjT3p/4.png",
    upliveName: "Newton",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Vladimir Herzog",
    referralName: "Griffin Berge",
    specialTalent: "Other",
    videoLink: "https://www.youtube.com/",
    recruitmentDate: "2022-04-20",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    id: "53637",
    email: "holly.rowe@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Rowe",
    firstName: "Holly",
    birthDate: "1992-12-03",
    gender: "Female",
    address: "3479 Verner Green Chehalis, WA 98532",
    country: "Australia",
    mobileNumber: "+1.420.588.1278",
    avatarImageUrl: "https://i.ibb.co/FJysnnd/5.jpg",
    upliveName: "Holly",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Tracy Bogisich",
    referralName: "Kylee Frami",
    specialTalent: "Dancing",
    videoLink: "https://www.youtube.com/",
    recruitmentDate: "2022-08-01",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    id: "22424",
    email: "harvey.cierra@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Harvey",
    firstName: "Cierra",
    birthDate: "1995-03-04",
    gender: "Female",
    address: "8163 Boyer Crest Coahoma, MS 38617",
    country: "South Korea",
    mobileNumber: "+14854672877",
    avatarImageUrl: "https://i.ibb.co/HYCG9F4/6.jpg",
    upliveName: "Cierra",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Anastasia Hyatt",
    referralName: "Karli Corwin",
    specialTalent: "Dancing",
    videoLink: "https://www.youtube.com/",
    recruitmentDate: "2022-08-12",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
  {
    id: "68943",
    email: "iva.boehm@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Boehm",
    firstName: "Iva",
    birthDate: "1998-02-07",
    gender: "Female",
    address: "704 Wolff Loaf Apt. 213 Penasco, NM 87553",
    country: "Canada",
    mobileNumber: "515-277-8087 x8624",
    avatarImageUrl: "https://i.ibb.co/9NxbJ81/7.jpg",
    upliveName: "Iva",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Dominique Zulauf",
    referralName: "Amira Renner",
    specialTalent: "Singing",
    videoLink: "https://www.youtube.com/",
    recruitmentDate: "2022-09-04",
    hasConfirmedEmail: true,
    createdBy: 1,
  },
]

exports.pendingHostsDummy = [
  {
    id: "25263",
    email: "lottie.goyette@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Goyette",
    firstName: "Lottie",
    birthDate: "1994-08-01",
    gender: "Female",
    address: "92353 Greenfelder Spring Apt. 980 Duncan, MS 38740",
    country: "United States",
    mobileNumber: "+1 (346) 491-3398",
    upliveName: "Lottie",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Crisostomo Ibarra",
    referralName: "Juan Dela Cruz",
    specialTalent: "Singing",
    videoLink: "https://www.youtube.com/",
    isRecruited: false,
  },
  {
    id: "63635",
    email: "penelope.conroy@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Conroy",
    firstName: "Penelope",
    birthDate: "2000-04-05",
    gender: "Female",
    address: "338 Tillman Path Suite 092 Encampment, WY 82325",
    country: "Japan",
    mobileNumber: "1-557-218-8572",
    upliveName: "Penelope",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Esther Mayert",
    referralName: "Fleta Robel",
    specialTalent: "Singing",
    videoLink: "https://www.youtube.com/",
    isRecruited: false,
  },
  {
    id: "57363",
    email: "reba.crooks@gmail.com",
    password: "$2b$10$UNp7XeNbTDxCo29yZDeUdus5yYUd3U5qqeiCT7/ODts/zJhdtje.C",
    lastName: "Crooks",
    firstName: "Reba",
    birthDate: "1997-08-02",
    gender: "Male",
    address: "935 Krista Dam Casselton, ND 58012",
    country: "Philippines",
    mobileNumber: "(768) 467-2658",
    upliveName: "Reba",
    instagramAccount: "https://www.instagram.com/",
    facebookAccount: "https://www.facebook.com/",
    tiktokAccount: "https://www.tiktok.com/en/",
    talentManager: "Antoinette Hammes",
    referralName: "Maureen Kerluke",
    specialTalent: "Singing",
    videoLink: "https://www.youtube.com/",
    isRecruited: false,
  },
]

exports.faqDummy = [
  {
    question: "Is there a way for me to update my personal details?",
    answer: "You can update your details by going to the 'My Profile' section from the menu (located on the left sidebar) or by sending a request to the administrators.",
    createdBy: 1,
  },
  {
    question: "How do you calculate the estimated payout for each month?",
    answer: "The formula for this calculation is as follows: number of uCoins divided by 210 (plus a bonus depending on which row your uCoins fall in the bonus payout table).",
    createdBy: 1,
  },
  {
    question: "What is the monthly quota for the number of uCoins?",
    answer: "You should aim to accumulate at least 30,000 uCoins for each month.",
    createdBy: 1,
  },
  {
    question: "What is the monthly quota for the number of stream hours?",
    answer: "You should aim to accumulate at least 30 stream hours for each month.",
    createdBy: 1,
  },
  {
    question: "What is the monthly quota for the number of stream days?",
    answer: "You should aim to accumulate at least 10 stream days for each month.",
    createdBy: 1,
  },
]

exports.announcementsDummy = [
  {
    title: "Welcome to the company",
    type: "Others",
    details: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    createdBy: 1,
  },
  {
    title: "Year-end party",
    type: "Reminder",
    details: "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem.",
    createdBy: 2,
  },
  {
    title: "Our new manager",
    type: "Others",
    details: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio.",
    createdBy: 3,
  },
  {
    title: "Update personal details",
    type: "Task",
    details: "Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
    createdBy: 4,
  },
  {
    title: "Submit gov't-related documents",
    type: "Task",
    details: "Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
    createdBy: 4,
  },
]

exports.calendarActivitiesDummy = [
  {
    title: "Summer vacation trip",
    type: "Reminder",
    details: "Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.",
    date: "2022-10-10",
    group: "Host",
    includeAllHosts: true,
    createdBy: 1,
  },
  {
    title: "Monthly team building",
    type: "Reminder",
    details: "Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus.",
    date: "2022-10-27",
    group: "Host",
    includeAllHosts: true,
    createdBy: 1,
  },
  {
    title: "General assembly",
    type: "Others",
    details: "Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.",
    date: "2022-11-15",
    group: "Host",
    includeAllHosts: true,
    createdBy: 1,
  },
  {
    title: "Weekly meeting",
    type: "Task",
    details: "At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident.",
    date: "2022-10-23",
    group: "Admin",
    includeAllHosts: false,
    createdBy: 1,
  },
  {
    title: "Annual performance evaluation",
    type: "Reminder",
    details: "Curabitur sit amet magna et turpis hendrerit eleifend. Morbi et ex cursus elit iaculis tristique sit amet ut dui. Ut faucibus, ex eget pharetra suscipit, lorem quam tincidunt eros, in ultricies metus lectus laoreet dui.",
    date: "2022-11-10",
    group: "Admin",
    includeAllHosts: false,
    createdBy: 1,
  },
  {
    title: "Planning for year-end party",
    type: "Task",
    details: "Nam iaculis lobortis tincidunt. Etiam vitae nunc diam. Phasellus non lacus ut felis blandit consequat ac non leo.",
    date: "2022-11-20",
    group: "Admin",
    includeAllHosts: false,
    createdBy: 1,
  },
]